### ISSUE TITLE
Flutter master channel

### ISSUE THREAD

**Issue by jonmountjoy** [rydmike/flex_seed_scheme#13]
When I try and use this package on the latest Flutter master (on a CI server), I get something like this:

```
The current Flutter SDK version is 3.22.0-36.0.pre.52.

Because flex_seed_scheme 2.0.0 requires Flutter SDK version >=3.22.0 and no versions of flex_seed_scheme match >2.0.0 <3.0.0, flex_seed_scheme ^2.0.0 is forbidden.
So, because myapp depends on flex_seed_scheme ^2.0.0, version solving failed.
```

I would have thought that `3.22.0-36.0.pre.52` is > than `3.22.0` but 🤷 but perhaps it's the designator for the build preceding the release of `3.22`.

I see the pubspec for flex_seed_scheme does have:

`flutter: '>=3.22.0'` which seems just fine.  

Does anyone perhaps have an idea how to address this?

**Comment by rydmike** [comment]
Hi @jonmountjoy, ouch, because usually when Flutter stable is released both beta and master get a minor version bump (.z+1), because as you noticed a x.y.z release is considered bigger than any x.y.z-a.b.pre.c, since a "pre" release" with x.y.z is supposed to come before its "just" x.y.z release.

Both beta and master should get a minor bump soonish, probable Google/Flutter team has not gotten around to it yet during and post Google I/O.

Not sure what I can do, well sure I guess I could release a "2.0.1-dev.1"version that is identical, but has its min version set to whatever beta is on now. If you need it really badly I can make this identical dev release that has the version constraint set to current beta version and higher, this should then work for both beta and master (and yes stable too).

**Comment by rydmike** [comment]
You can try this using this release on **beta** and **master**, should work on **stable** too.
https://pub.dev/packages/flex_seed_scheme/versions/2.1.0-dev.1

Its changelog.

https://pub.dev/packages/flex_seed_scheme/versions/2.1.0-dev.1/changelog

I will also use this dev release to test some new `FlexTones` later. Those will come in `2.1.0-dev.x` bumps, by bumping x version.

**Comment by jonmountjoy** [comment]
That's kind of you to roll that out for such an esoteric (and hopefully very temporary) bug - thank you @rydmike 
This has enabled me to get a build through.  There's a nasty regression in 3.22.0 which stops textfields from working - no matter what colour they are :-) https://github.com/flutter/flutter/issues/148573
